### ISSUE TITLE
token-transformer merges tokens before deciding what set to exclude

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#1182]
If you have the following structure:
```
themes
  Foundations
  Light
  Dark
```

and the "Dark" theme is setup like this:
```
Foundations: SOURCE
Light: SOURCE
Dark: ENABLED
```

And your Light theme contains all tokens that the dark theme uses:

```
Foundations:
{
  "color": {
    "neutral": {
      "10": {
        "value": "#E6EFFF",
        "type": "color"
      },
      "50": {
        "value": "#2B70E8",
        "type": "color"
      }
    }
  }
}

Light:
{
  "default": {
    "value": "{color.neutral.50}",
    "type": "color"
  },
  "gray": {
    "value": "{default}",
    "type": "color"
  },
  "background": {
    "value": "{color.neutral.10}",
    "type": "color"
  }
}

Dark:
{
  "gray": {
    "value": "{default}",
    "type": "color"
  },
  "background": {
    "value": "{color.neutral.10}",
    "type": "color"
  }
}
```

And you want to transform this with token-transformer like this:

`npx token-transformer themes output.json Foundations,Light,Dark Foundations,Light`

Your output file will be empty. Reason for that is that we probably merge tokens before we decide what to exclude. Ideally, something set as SOURCE doesn't overwrite something set as ENABLED, and we don't remove tokens that are part of any set that is ENABLED.

**Comment by krizkonte** [comment]
I think that I having a relationed issue.

Imagine that I got 3 sets:
* core (source)
* desktop(enabled)
* mobile(enabled)

If I try to select a single set as:
`token-transformer tokens.json core.json **core** `
This works is fine, and i got only de core tokens only.

But if i try too use 2 sets like:
`token-transformer tokens.json core.json **core,desktop**`
This already return a blank json, even if I do not use the excludes command.

**Comment by alecgeatches** [comment]
Just to tag on with a similar problem that may be related from the issue description:

> Ideally, something set as SOURCE doesn't overwrite something set as ENABLED

We have a font family in our core set of tokens `globals` and are overriding it in an enabled set. From `globals`:

![core-font-family](https://user-images.githubusercontent.com/17870752/192201385-327e589a-f96d-4af9-a537-5fc988f3f017.png)

In an enabled token set `expressive-type` we're overriding the font set with `Aktiv Grotesk VF` and use a reference to it:

![theme-font](https://user-images.githubusercontent.com/17870752/192201636-1233a30d-db1d-408b-981b-354a3871bd61.png)

We run `token-transformer` with `globals` as a source:

```
token-transformer tokens.json transformed-tokens.json --throwErrorWhenNotResolved --expandTypography=true globals,expressive-type globals
```

The resulting output uses the core value of `Helvetica` instead of `expressive-type`'s override value:

![transformed-tokens](https://user-images.githubusercontent.com/17870752/192203130-5730c9f2-152f-4a26-809a-ec5aaa834045.png)

We're able to work around by removing `fontFamily` from the `globals` set, but ideally we could override the base font settings per-theme. Is this the same problem, or something else?

Thank you!
