### ISSUE TITLE
Performance issues with increasing numbers of tokens

### ISSUE THREAD

**Issue by engegu** [six7/figma-tokens#138]
I am experiencing wait times of around 1 minute every time i add or change something in Figma Tokens, due to the app updating. This occurs both with JSON files synced to JSONbin and when i uncheck that for local storage.

Is there anything that can be done about it? Maybe an option to update the file manually instead of after every change?

We have a substantial amount of tokens, both global ones and component specific ones which reference the global ones for their values. If we have to go for a simpler scheme it will be less valuable to us.

Hopefully something can be done?

**Comment by six7** [comment]
Hey @engegu 

#123 addresses this issue and is already in the `next` branch due to be released. It will allow you to disable the update on change feature that basically performs very cost-intensive traversal of all layers of the current page after each token change.

Its not the nr. of tokens thats expensive, its the number of layers. What you can do now, and I now that's might not work for you, is to perform token edits on smaller pages. Once #123 lands you'll be able to edit tokens and update when you feel like it (which will take it's time if done for the whole page)

I do hope to release it soon to beta testers (taking a bit longer because of a larger refactoring that took place). If you'd like to help beta test, let me know!

**Comment by engegu** [comment]
Sounds great, will try the small page workaround for now. I'd be happy to help beta testing. My Figma acct is: engebret.gudbrandson[at]bouvet.no
