### ISSUE TITLE
Active Token Sets not retained on Plugin Close

### ISSUE THREAD

**Issue by JoshMormann** [six7/figma-tokens#155]
Editing a tokenized document without checking for the state of the plugin's active token sets can lead to editing the wrong token definitions, or appear to, since the last active token set is the one you will see visible in your document, while when reactivating the plugin will show only the first set as active. This is confusing, and frustrating at the least, but I fear without my diligence in checking it regularly, that I might inadvertently create inconsistencies.

**Comment by six7** [comment]
I get where you're coming from, I've had this pain point before.

**Possible solutions I've thought about:**
- A: Store the active token sets that were used on the document
- B: Store the active token sets that were used on the token storage (Jsonbin e.g.)

**Both have downsides:**
A: When storing on the document, what if a user changes / deletes / updates their token sets somewhere else while the plugin isn't open (I'd suggest falling back to the current behaviour in that case). I think this case would only appear when users change / delete token sets someplace else and might be an edge case.

B: When storing on token storage: Active token sets could differ between different documents, so that option isn't really valid.

I might miss a better solution, but what would you think of solution A?

**Comment by JoshMormann** [comment]
I think Solution A would be best, because I am not so sure all users will also be using JSONbin.io as a token value transference mechanism. FT is so robust just as a style management and theming powertool, within the figma realm itself, that I imagine many will use it purely for DS manipulation and use their own home grown output paths. I feel like the figma document should be the single source of truth by default. IMHO.

Again, thank you for all your work on this.
