### ISSUE TITLE
How do we go grouping of colors in the new version?

### ISSUE THREAD

**Issue by senthil87** [six7/figma-tokens#182]
Hi Jan, 
It's a great release with a lot of new features. Is there an option so that we can still use the older method? We have already defined the workflow using the older version and all of our components are updated with that tokens. Now with the new approach, the token names are completely changed and the whole token approach is messed up. Also, with the newer approach where we are using the 'type' and all the colors are now in one single bucket and there are no groupings (attached the screenshot). 
<img width="393" alt="Screenshot 2021-08-02 at 11 19 25 AM" src="https://user-images.githubusercontent.com/5101306/127810442-4fea3231-4aa1-4fd4-a7a5-f0d24e4e21ec.png">

Is there a way we can still maintain the grouping like before?

**Comment by senthil87** [comment]
I have found that if the json has the property called "name", the plugin takes the name as the token name and resets everything.

**Comment by six7** [comment]
Thanks for filing this issue. Even though the new release was beta tested extensively it seems this must've slipped through.

Just so I get it right: your old JSON had a `name` property on each token defined that was set up like this:

```
colors: {
  primary: {
    500: {
      value: '#ff0000',
      name: '500'
    }
  }
}
```

And now the plugin treats all these tokens as if they were part of the same bucket, right?

Basically what changed is that the manual creation of empty folders was removed because the new token structure doesnt allow empty groups (much like Figma's styles). I'm thinking in your case it had to do with that name property you had on your tokens (which the plugin uses internally) confused the plugin as the plugin basically stores a `name` prop on each token with the full name of the token (in the above example `colors.primary.500`).

Could you also maybe share a file with me or the old or new JSON?

**Comment by senthil87** [comment]
We are using the JSON generated by Style dictionary and by default it had name property in it. I have removed the name property from the JSON and now things are working like before. So for now I will go ahead with that option.

**Comment by six7** [comment]
Got it, will rename that field internally as that name prop probably is required for SD I guess.

**Comment by senthil87** [comment]
That would be awesome. Thank you so much for your time and great work.
