### ISSUE TITLE
Math not properly evaluated

### ISSUE THREAD

**Issue by coolmanlume** [six7/figma-tokens#209]
**Describe the bug**

With the JSON sample below, the evaluation should deliver:

TKM.scale.seqArithNd.1200 = 96  (aka 64 * 1.5)

but delivers:

TKM.scale.seqArithNd.1200 = **92**

> TKM.scale.seqGeo.400 = 8   // correct
> feeds ↓ :
> TKM.scale.seqArithSt.1100 = 64    // correct
> feeds ↓:
> TKM.scale.seqArithNd.1200 = 92  // **incorrect, should be 96**

**To Reproduce**

Paste the JSON inside Figma Tokens, and do the math yourself to compare:

```json
{
  "TKSC": {
    "scale": {
      "base": {
        "value": "2",
        "type": "sizing"
      },
      "ratio": {
        "value": "2",
        "type": "sizing"
      },
      "baseIndex": {
        "value": "400",
        "type": "sizing"
      }
    }
  },
  "TKM": {
    "scale": {
      "seqGeo": {
        "400": {
          "value": "$TKSC.scale.base * $TKSC.scale.ratio ^ round((200 + 400 - $TKSC.scale.baseIndex) / 100)",
          "type": "sizing"
        }
      },
      "seqArithSt": {
        "1100": {
          "value": "$TKM.scale.seqGeo.400 + $TKM.scale.seqGeo.400 * ((1100 - 400) / 100)",
          "type": "sizing"
        }
      },
      "seqArithNd": {
        "1200": {
          "value": "$TKM.scale.seqArithSt.1100 * 1.5",
          "type": "sizing"
        }
      }
    }
  }
}
```
**Screenshots:**

| 64 | 64 * 1.5 ≠ 92 |
| --- | --- |
| ![Screenshot 210823-063013](https://user-images.githubusercontent.com/12875139/130456058-835d6503-010b-4a06-bf59-7f8a69760e75.jpg)|![Screenshot 210823-063042](https://user-images.githubusercontent.com/12875139/130456079-718754b4-104f-45fe-8eae-05bd9393a18f.jpg)|

**Comment by six7** [comment]
Thanks for reporting this, there seems to be an issue with math multiple levels deep.

We're not encapsulating each calculation on its own, as we should. Instead your calculation boils down to `8 + 8 * ((1100 - 400) / 100) * 1.5` which is, in fact, 92.

We should probably encapsulate each calculation on its own instead of resolving each alias and THEN doing the calculations.

For the short term your problem can be solved by defining `TKM.scale.seqArithSt.1100` as `($TKM.scale.seqGeo.400 + $TKM.scale.seqGeo.400 * ((1100 - 400) / 100))`
