### ISSUE TITLE
Calculated values are not respected in variables

### ISSUE THREAD

**Issue by netleader** [six7/figma-tokens#2407]
Same as in [#2059].

Expected:
40 + 40 = 80

Current State:
{core.spacing.1000} + {core.spacing.1000}  = 0

Looks like you guys broke something with the last update, I restarted Figma x times, recreated the variables x times. Nothing helped.

**Comment by keeganedwin** [comment]
Hey @netleader, this is a bit of a known issue since our recent release has some major issues concerning tokens and variables. We have since released a roll back version to fix the bugs that were present in recent release, but users have still been pointing out flows that concern variables are not 100% working as expected. 

In the comments of the following ticket, you should find the fix (#2400) for tokens and variables, but this hasn't been merged and released yet which is probably why you are still facing an issue: #2399

**Comment by esthercheran** [comment]
@netleader are you still facing the issue in release 1.38.6?

**Comment by esthercheran** [comment]
@netleader can you click on the `Sync Variables` and check once

**Comment by esthercheran** [comment]
Would it possible to DM me on the Tokens Studio chat?
