### ISSUE TITLE
UI for batch action: delete, rename & drag category

### ISSUE THREAD

**Issue by jyun914** [six7/figma-tokens#291]
**Use case**
- User builds tokens without using "import"
- Naming convention has not been fully determined
- Categorization method has not been fully determined
- User has to remove, edit & organize categories as they test different approaches

**Curren method**
- Edit name, remove, organize in JSON file

**Proposed Update**
- Rename & remove by clicking on the category name on the UI
- Reorganize orders by click-drag on the category
- Click-drag tokens in/out of a category

**Bonus**
- Auto-fill or type-ahead suggestion on certain input fields (esp. typography where you have to insert several references).

**Comment by six7** [comment]
So I think there's 3 features here:

- refactor when renaming: covered in #247 and #211 and #165 
- sort tokens in ui covered in: #122 
- type ahead, something like react-mentions: https://react-mentions.vercel.app/ - could you create an issue for that? i tried something like this out locally but discarded due to it leading to a broken experience at times. Typeahead would be great, but at the same time a simple token chooser could be good already. like a color picker but for picking token values.

If it's OK with you I'd close this issue once the type ahead one is created?

**Comment by jyun914** [comment]
@six7 All of this makes sense. The new update is awesome. Thanks for your hard work on this. 
I made a new ticket for the token chooser. Please feel free to close this one.

**Comment by six7** [comment]
Perfect, thank you for creating that issue. Will close this one, let's discuss in the other issues on each of these on their own
