### ISSUE TITLE
JSON available for library assets

### ISSUE THREAD

**Issue by AlexeyNovik** [six7/figma-tokens#363]
**Is your feature request related to a problem? Please describe.**
I am working with a huge library which is tokenized.
When I am using assets from the library added to the file, I see that tokens are applied to the asset, but JSON does not present.

**Describe the solution you'd like**
When the library is added to the file the JSON should also be instantly available in Plugin.

**Describe alternatives you've considered**
Now I need to do a manual copy-paste of the JSON, which lead to several "style resets". Manual editing is not an option.

**Comment by six7** [comment]
What I'd advise here is to use the Sync function of the plugin to have one common source across all documents and team members.

Here's more on that: https://docs.tokens.studio/sync/sync

The reason why it's not stored on a library asset is because we'd want those assets to be `headless` in theory, so you could change source of truth and have a different style applied.

**Comment by six7** [comment]
Closing this one as we'd want to have our components be independent from the values of tokens.
