### ISSUE TITLE
Bug: color style tokens have 'internal__Parent":"dark","rawValue":"{Colors.Blue200}"}' discrepancy 

### ISSUE THREAD

**Issue by maartensaulx** [six7/figma-tokens#366]
**Describe the bug**
I use the plugin to define tokens and switch theme, I don't use the plugin to apply tokens to shapes etc. (as described in the doc.)
The bug appears when I open the plugin and inspect a certain component I made. The component has a color style but in the plugin it does not show the matching token. It shows a completely different token. When I inspect the discrepancy, I see something odd in the token's name: "Internal__Parent:"dark","rawValue":{Colors.Blue200}. That is also the reference to the color token that is highlighted on selecting the component.

[See video for explanation. ](https://youtu.be/u_NV4mpl9jA)

**Comment by six7** [comment]
The reason for that is that the plugin looks for local styles that match the token name you applied. In your case that matched, but the value of that style is black instead of blue.

What I do is something like this, where I don't apply any color or typography tokens but completely rely on Figma styles to do that. I use the plugin to manage these styles and use other tokens which Figma didn't introduce (yet), like described here: https://jansix.at/blog/creating-design-systems-based-on-design-tokens-figma-tokens

We'll be making some changes in the future to better address this 🙏 Especially with https://github.com/six7/figma-tokens/issues/145 this will be easier.

Closing this for now as it is mostly tied to that issue.
