### ISSUE TITLE
Provide an option to disable auto-sync when opening the plugin

### ISSUE THREAD

**Issue by ekfuhrmann** [six7/figma-tokens#390]
**Is your feature request related to a problem? Please describe.**
If you have sync set up with something like Github, any changes you may make locally can be deleted by mistakenly closing the plugin window since when it re-opens, it auto-syncs back to Github.

**Describe the solution you'd like**
Provide an option in settings to disable auto-sync, requiring users to actually pull changes so as to not override local changes before committing.

**Describe alternatives you've considered**
Committing on every change so as to not lose work.

**Comment by six7** [comment]
Thanks for the suggestion! The problem at hand rather has to do with the fact that when using GitHub sync the local storage isn't saved between plugin sessions. https://github.com/six7/figma-tokens/issues/353 will tackle this.

I would see your suggestion as part of that feature, so that when you open the plugin and your local changes are different to what's stored on remote, the plugin would somehow tell you that you have changes that are different to the remote (kind of like VSCode has a differentiator between no. of pull/push commits).

I'm leaning towards closing this one and making sure the needs of this issue are tackled in #353.

**Comment by ekfuhrmann** [comment]
#353 looks like it will solve this issue if you want to close and consolidate it to there.

**Comment by six7** [comment]
Closing this in favor of #390 - updated description to make sure we address not auto-syncing on opening the plugin.
