### ISSUE TITLE
Docs about JSON structure

### ISSUE THREAD

**Issue by starzonmyarmz** [six7/figma-tokens#431]
**Is your feature request related to a problem? Please describe.**
I'm in the process of making tokens available as JSON in our Storybook implementation. I'm struggling to figure out the best way to structure the JSON in a way that Figma Tokens can work with. The documentation regarding this seems to not exist. It's been a lot of trial and error up to this point trying to figure it out.

**Describe the solution you'd like**
It would be helpful if there were some docs that cover JSON structure, and maybe even recommended best practices.

**Comment by six7** [comment]
Great idea, this is something that's poorly covered.

A rough structure for files stored on GitHub looks like this:

```
{
  set1: {
    group: {
      spacingtoken: {
        value: string | number,
        type: spacing
      }
    },
    group2: {
      shadowtoken: {
        value: object | object[],
        type: boxShadow
      }
    },
    group3: {
      typographytoken: {
        value: object,
        type: typography
      }
    }
  },
  set2: {
    group4: {
      colortoken: {
        value: string,
        type: color
      }
    }
  }
}
```

i think it would be great if we had something like this that also covered token types and what values they can have.

**Comment by mryechkin** [comment]
Agreed 💯 I've just started exploring the plugin, and I'm running into issues with trying to create tokens via JSON first, rather than through the plugin GUI. It would be great to have more detailed docs, or even just a link to a sample JSON file - would help a great deal with debugging some problems. At this stage I'm not sure if it's something wrong with my JSON structure, or something in the plugin itself.

**Comment by six7** [comment]
Added a first version of this to https://docs.figmatokens.com/tokens/json-schema which we'll improve in a coming docs rehaul, closing this issue for now 🙏
