### ISSUE TITLE
Color styles are replaced with hex values when token set is switched in a remote file

### ISSUE THREAD

**Issue by kmiters** [six7/figma-tokens#466]
**Describe the bug**
I have a design system library file in which I defined the colour tokens and two token sets (for light mode and dark mode). When I switch token sets in the design system file everything works as expected. But in a second file to which I imported the design system as a library when I switch the token sets all the colour styles are replaced with hex colour values. 

If that matters at the moment I'm using JSONbin to sync the tokens between the files (but I don't think so because the JSON file looks the same for both files).

Am I doing something wrong or is it a bug?

**Expected behavior**
I would expect that in both files when I switch the token sets the colour styles are preserved.

**Comment by six7** [comment]
This is because we don't store the ids of Figma style associated with a token currently.

It's a bit tricky as tokens can be influenced by previous themes, so we wouldn't automatically know which style belongs to which token.

Here's an issue tracking this: https://github.com/six7/figma-tokens/issues/145

**Comment by kmiters** [comment]
Thank you @six7 for the reply. I'm waiting with bated breath for the fix ;-)

**Comment by six7** [comment]
Closing this one, let's keep discussion going in #145
