### ISSUE TITLE
(Andreww16 from Figma community) - Deep Inspect & remove-all feature still leave some stray left overs...

### ISSUE THREAD

**Issue by AW85** [six7/figma-tokens#489]
Dear all, 

My nick name is Andreww16 from Figma Community and I have been posting my concerns, as context reminder going back since last year 2021 over how to "undo" all my Tokens into my design system (which ran last time based off memory ~ up to 10,000+ nodes registered somehow). The significant performance slow downs inbetween general actions in Figma deteriorates badly enough that I started raising this in the Figma Tokens page.  

**My goal / request is hopefully not too complicated : find a way to completely remove any or all tokens. So that when time is right - I shall try once again implementing the Tokens System from scratch.** 

However the many month(s) passed after I tried "clearing" everything, from token entries, categories, JSon etc the plug-in made my entire Design system and general workflow ~ unresponsive. I decided to give up and left everything as is as I decided to instead evolve the design system conventionally (new components, .base/structures for different contexts,scenarios etc). 

Fast forward now in February 2022; realizing that "Deep Inspect" and the Remove-All feature is available I decided to give it a try artboard per artboard. And sadly it does not remove any or all Tokens and some stray left-overs somehow remain. I uploaded a Youtube unlisted video on this issue [as]([https://youtu.be/M7Qk1unp5eE](https://www.figma.com/exit?url=https%3A%2F%2Fyoutu.be%2FM7Qk1unp5eE)) have I in the Figma Tokens community page.  

I have created a github account solely just to raise this issue request in the eventual hope that this is attended to. 

To JanSix and Abdul Wahid I thank you for bringing the Tokens into the Figma community. I honestly do support the Tokens Plugin. However currently as it stands ~ the logistics, practicality and methodology concerns in my humble opinion ~ may yet demand a learning curve of its own.

Once again, thank you for responding to this issue. 

Andrew / Andreww16 (@Figma nick)

**Comment by six7** [comment]
Thanks for creating an issue here, it's far easier to work on this. Figma community isn't great when it comes to feedback like this as you have no way to reply to people.

When you do remove those tokens and they keep showing up: Did you try the latest version? I've fixed something since you last posted your video. I'd really like to find out why it's not removing those tokens for you.

Also, if you can share a file with me, I'd appreciate that so I could give it a go. You can send the invite to six.jan@gmail.com

**Comment by AW85** [comment]
Jsix / Six7

Thank  you so much for responding me much appreciated.

I decided to share with you my entire Design System. Yes, I know - it's very complex but my approach is   to hopefully integrate both Design System and a Kit  all in one...

I know you are much busier   elsewhere, I myself would not, as my confidence currently stand - to reintroduce the tokens system anytime soon so hence I would lower this priority as low to moderate in your midst of obligations.

I decided to share and invite you to directly. 
https://www.figma.com/file/RFFT6uQW6XvHHB0kUklrjv/DS-1_9_1-(backup-for-Tokens-Support)

It is quite late here from where I am down under, so hence take your time and  I shall only respond when I'm back come daylight. 

sincerely,

Andrew.

**Comment by six7** [comment]
Hey Andrew,

I was able to find out what causes that behaviour.

The reason for this is that you have instances of components that you removed. The plugin couldn't remove these as it just doesn't have access to any removed main components.These tokens reappear is because of how component overrides work inside Figma. If the instances doesn't have an override on that particular token, it would show what's stored on the main component. As this one doesn't exist, it cannot be deleted. I would suggest you restore those removed components and remove tokens that are stored there.

https://user-images.githubusercontent.com/4548309/155947596-f6af4c89-f9a8-4ed5-a7e7-fa9fde7a4491.mp4

**Comment by AW85** [comment]
Six7,


I truly did not expect a reply from you soon. You have  my sincere gratitude. 

I shall have to spend some time re-analysing and re-investigate, as you suggested ~ to somehow find and restore somehow lost or "orphaned" components (I hope I'm using the right analogy here)... 

This will take  some  time for me to respond, however in the mean time,,, please I   encourage you to attend to other higher   priorities.

once again, thank you so much for bringing this attention for me. 

regards and I;ll strive to respond within two days depending how ready I am with any more results.

Sincerely,

Andrew.

**Comment by six7** [comment]
I'll be closing this issue for now - feel free to reopen if there's anything else that can be done 👍
