### ISSUE TITLE
[Inspector]:  Show all layers using a token in Inspect panel

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#513]
From Slack

:bulb: Show all usages in Inspect panel
Firstly, the Inspect panel is really shaping up, nice work, and thank you Jan :clap:
Context: We're currently using the Inspect panel to analyse how many tokens are being used, and how many times each token is being used in a given page. To do this, we select every object in a page and then open the Inspect panel.
:bulb: Idea: From here, it would be really neat to then be able to gather a list of all objects that are referencing a given token.
Perhaps by clicking the number of objects, on the right of the token (screenshot 1)?
Something similar to this is the [Instance Finder plugin](https://www.figma.com/community/plugin/741895659787979282/Instance-Finder) (screenshot 2).

![image](https://user-images.githubusercontent.com/4548309/157412649-0193328c-b85f-48c4-bfcc-6a5764af0b94.png)

![image](https://user-images.githubusercontent.com/4548309/157412668-9355ece5-ceb4-4127-b8b6-1948245dc068.png)

**Comment by samwalshnz** [comment]
To answer a couple questions from the [original Slack thread](https://figmatokens.slack.com/archives/C02JAL48UDN/p1646817982913679?thread_ts=1646280894.662579&cid=C02JAL48UDN):

--- 

> @six7:
> What would you like to do with that list then, be able to jump to them, select/deselect some?

Yeah, pretty much, and potentially then update them by applying a different token value.

For context, we're in the early stage of build a design system for an already existing web app. We're currently refining our spacing system, exploring the feasibility of reducing the number of increments (and complexity) in our spacing system.

e.g.
If I select a frame containing a full-page design, in the 'Inspect' tab of Figma Tokens I can see that our mockup we are using _8 spacing sizes_. Does our design _need_ all 8 spacing sizes, or can we reduce the number of spacing units without compromising the design?"

In this scenario, the initial value add in Figma Tokens was the ability to quickly highlight _how many_ spacing sizes we were using. The ideal next step would be to be able to then visualise (or list) which layers/objects in the selection are using a given token so that we can identify (visually, in the context of the design) if that special spacing size was necessary or whether it could have been swapped out for a similar size.

**A potential solution:**
1. Clicking on the number of layers (sitting to the right)
2. The nodes selected then switch to only selecting the individual layers that have that token applied.
3. Using only existing functionality in Figma Tokens, with all the applicable layers currently selected, I could then bulk-change all layers and  _apply_ a different spacing token, from within the "Tokens" tab.

---

> @six7:
> We’ve thought about giving users a way to only select tokens that contain a given token (something like reduce selection to only those layers using that token) but I think your request goes in a different direction, both seem useful!

That would also be a very helpful! But yeah, I think that feature would kind of be the _inverse_ flow of what I was thinking.
