### ISSUE TITLE
JSON input may leave Plugin unusable

### ISSUE THREAD

**Issue by caboe** [six7/figma-tokens#70]
Steps to reproduce:

1. Open Plugin
2. switch to JSON tab
3. enter JSON, where a variable does not represent a string value, but an object:
`{
  "primitives": {
    "gap": {
      "xs": "4px",
      "s": "8px",
      "m": "16px",
      "l": "32px",
      "xl": "64px"
    }
  },
  "spacing": "$primitives.gap"
}`
4. click "Save & update"
5. Click on Tokens

After that, the plugin box stays empty. And I did not find a way to reset it. Even uninstall and reinstall the Plugin does not help.

Questions:

1. Can you avoid this behavior in the plugin? 
2. Is there a way to reset the plugin, so I can again post the JSON?

**Comment by six7** [comment]
Thank you for reporting this, @caboe ! This is caused by a bug also reported in #72 — I fixed this just now and will get that fix online later today.

However, one thing you're trying in your example is to link `spacing` to the object `$primitives.gap` -> this is something that's not possible at the moment — aliases have to be single tokens I'm afraid. I will create a new issue for this specifically though, as I would also like to have this feature! 🙏
