### ISSUE TITLE
Ability to resize plugin window

### ISSUE THREAD

**Issue by bzupancic** [six7/figma-tokens#87]
Before the update I wanted the ability to resize the window to make the JSON more readable. With the addition of token-sets I want it even more.
I use 4 themes, default, gray-10, gray-90, and gray-100. Due to the constraints on the plugin window, the text wraps and makes the set names difficult to read.

**Comment by six7** [comment]
Great idea! I'm thinking of adding this as an option in a new Settings screen (we will have some options that the user might want to define).

This is an option that I would store on the device, so that when you later restart Tokens, the size should stay the same as you previously set.

Would you say you'd want flexibility when it comes to resizing? Or would being able to choose from a set of options be enough for you?

Figma allows us to resize the UI on the fly: figma.ui.resize(width, height)
https://www.figma.com/plugin-docs/api/figma-ui/#resize

**Comment by six7** [comment]
As a quick fix for you until we have this working:

1. Go into console (F12)
2. Type: `figma.ui.resize(640, 480)` 
3. Type enter

The size of the UI will now resize according to your dimensions.

**Comment by bzupancic** [comment]
Ultimately, flexibility would be the best. That way, no matter the line length in the JSON editor or space needed for token-sets, the user could decide. That being said, if preset sizes is an easy win, then I will take it :)

You have been super responsive to these issues, I really appreciate it.

**Comment by GUESShimself** [comment]
+1 for flexibility over static size options as well, and for the same issue of having multiple Token Sets becoming unreadable.

Horizontal scrolling of the Token Sets row would also suffice, but resizing the plugin window sounds like an all-around win.

**Comment by six7** [comment]
> +1 for flexibility over static size options as well, and for the same issue of having multiple Token Sets becoming unreadable.
> 
> Horizontal scrolling of the Token Sets row would also suffice, but resizing the plugin window sounds like an all-around win.

Woops, just checked. You're right. We had a horizontal scrolling bar for token names but that must've stopped working. Will investigate.

**Comment by six7** [comment]
Just merged this. Will publish a new version later in the day that allows you to set window size specifically (width px, height px), and store your values so when you restart the plugin it remembers your choice.
