### ISSUE TITLE
Plugins crashed on import styles

### ISSUE THREAD

**Issue by andywd7** [six7/figma-tokens#90]
Hi,

With a clean install of the plugin I try to import styles but the plugin crashes and white screens. If I uncheck the options checkbox and import styles then styles seem to be imported fine. However if I then close the plugin and reopen it then it is blank again?

I've attached 2 recording to help.

https://user-images.githubusercontent.com/1845961/112463302-fb245480-8d59-11eb-8d15-bc9a73079d10.mov

https://user-images.githubusercontent.com/1845961/112463379-1000e800-8d5a-11eb-98f1-6e67c3be2d30.mov

I hope this helps and that you can help? This has been such great work so far!

Thanks

**Comment by six7** [comment]
Thanks for raising this issue @andywd7 ! Could you by any chance share the Figma file with me? So that I could reproduce it? If you could email me at six.jan@gmail.com then I could take a closer look 🙏

**Comment by andywd7** [comment]
@six7 I've duplicated the file and shared it with you. Let me know if there are any issues 👍

**Comment by six7** [comment]
Thank you! I found the root cause:

Your typography tokens have one group named `.docs` - the plugin uses dot notation to create groups, so it basically created an empty group and was then unable to find aliases for your values. I'll publish a fix later in the day, so the plugin will stop looking for aliases after a few retries.

**Comment by andywd7** [comment]
Awesome thank you very much! Thankfully it was a simple thing. I can just rename that group with an underscore in the meantime 👍
