### ISSUE TITLE
Richer typography control

### ISSUE THREAD

**Issue by bzupancic** [six7/figma-tokens#95]
I am wanting to set 'underline' and/or 'strikethrough' text decorations for certain text styles. I may be using the wrong syntax, but typography 'decoration' doesn't seem to be supported.

Ability to set letter casing (uppercase, lowercase, titlecase, smallcaps) would be super useful as well.

**Comment by six7** [comment]
Agreed, that would be awesome! It's not in the plugin currently. I'm planning a overhauled typography edit experience, where not only you'd be able to set these properties but also get suggestions for font name and available font weights (similar to how I solved it in Batch Styler).

We're restricted by what Figma allows us to do, though. everything you mentioned is possible, according to the plugin docs:
https://www.figma.com/plugin-docs/api/TextStyle/#docsNav

I think the raw values first would be a good start (and easy to implement). The UI for that is something that would follow. 

I'm split between offering the same UI figma offers (on/off toggles) vs. real token values (so that you could reference `$textDecoration.headings`). I'm leaning towards token values, and maybe define the decoration toggle in a boolean way.

```
TextCase
type TextCase = "ORIGINAL" | "UPPER" | "LOWER" | "TITLE"
The possible values are:

"ORIGINAL": show the text as defined, no overrides.
"UPPER": all characters are in upper case.
"LOWER": all characters are in lower case.
"TITLE": all characters are in camel case. This is the "Capitalize" option in the UI.
```

```
TextDecoration
type TextDecoration = "NONE" | "UNDERLINE" | "STRIKETHROUGH"
The possible values are:

"NONE": the text is shown without decorations.
"UNDERLINE": the text has a horizontal line underneath it.
"STRIKETHROUGH": the text has a horizontal line crossing it in the middle.
```

**Comment by coolmanlume** [comment]
Hi Jan,
I second this request. And I like your proposal: the all-caps (for our eyebrows) would be an important addition.
What about [text alignments](https://www.figma.com/plugin-docs/api/TextNode/#textalignhorizontal)?

**Comment by six7** [comment]
> Hi Jan,
> I second this request. And I like your proposal: the all-caps (for our eyebrows) would be an important addition.
> What about [text alignments](https://www.figma.com/plugin-docs/api/TextNode/#textalignhorizontal)?

Alignments should be there as well, I agree!

**Comment by six7** [comment]
This feature will be released with Version 68 with a couple of minor adjustments:

Possible values will be:
textCase: `lowercase`, `uppercase`, `capitalize`, `none`. These will map to Figma's `LOWER`, `UPPER`, `TITLE`, `ORIGINAL`.
textDecoration: `underline`, `line-through`, `none`. These will map to Figma's `UNDERLINE`, `STRIKETHROUGH`, `NONE`.

I will not be able to include SMALL_CAPS and SMALL_CAPS_FORCED as it does not exist in Figma's PluginAPI yet. I created a feedback post in their forum: https://forum.figma.com/t/plugin-api-is-missing-textcase-properties-small-case-and-small-case-forced/9945

Also, I will not include textAlign in this initial release as textAlign is not part of Figma's styles. I will address this at a later point so that it can be part of a token but Figma just doesn't handle this information, but you could do something with it in development.

**Comment by six7** [comment]
Update: It seems SMALL_CAPS and SMALL_CAPS_FORCED are working, they're just not documented. There seems to be a bug with Figma not updating the styles correctly, but reading and setting them work.
