### ISSUE TITLE
URL sync doesn't have support for $themes object

### ISSUE THREAD

**Issue by shedali** [six7/figma-tokens#964]
attempted to use URL to a gist
https://gist.githubusercontent.com/shedali/034aa26437232a6fc7b9ec4a2d5cdc99/raw/92e0f0cd45309c89a3a4a04e18bff7f525f8805d/design-tokens.json

Receive error in plugin 
![image](https://user-images.githubusercontent.com/64362/177146285-5a1afb3f-b74f-4bb4-8ed6-6d4c1e19236d.png)

However the network tab shows a 200 success response with the full payload.

Similarly using jsonbin as endpoint in the url sync tab
headers: { "X-Master-Key":"$2b$10$a53jnqUhVtfp9cSLHZEy9ullNNRg3REVHGqPkwqnmhm6D8br/5Enu", "X-Access-Key":"$2b$10$h.j7MhvlVb4XmaZuGJDqSulPb4xPifIlOiQcqaHLr9BNY0tHmC.5G " }
url: https://api.jsonbin.io/v3/b/62a9df97402a5b3802291976

- using a GitHub repository in url sync works
- i.e. url https://github.com/shedali/tmp-tokens-test/blob/main/tokens.json
- however observe pressing edit then save causes a new credential item to be created which cannot be removed
![image](https://user-images.githubusercontent.com/64362/177164926-58dd0ece-0aab-441c-a22c-c3128f8fc284.png)

**Comment by six7** [comment]
Thanks for reporting!

The duplication error is already solved in the `next` branch which will be released soon.
 
As for the other issue: I discovered that this has to do with the empty $themes object. Can you remove that `$themes` key? We'll work on enabling support for that, I'll use this issue to track the work on that.

**Comment by shedali** [comment]
same issue with this url without themes object https://api.jsonbin.io/v3/b/62d4b5afb34ef41b73c60c6c

**Comment by LiamMartens** [comment]
@six7 this may already be fixed, because the `singleFileSchema` contains the `$themes` object already. Did we have the example JSON they used?

**Comment by six7** [comment]
> @six7 this may already be fixed, because the `singleFileSchema` contains the `$themes` object already. Did we have the example JSON they used?

The problem lies in the validation of URLTokenStorage when it's using the format without the `values prop`. If no `$themes` key exists, it works. If it exists, it doesn't (because it doesn't expect it).

Try to add the following URLs to URL sync:

This URL works: https://raw.githubusercontent.com/six7/tokens-storage/main/without-themes.json
This URL doesn't: https://raw.githubusercontent.com/six7/tokens-storage/main/with-themes.json

When console logging the validation it shows that zod is expecting an object, but the `$themes` property is an array.
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/4548309/179910797-b724bee0-1c8d-4fe2-975e-ea7ac45c5d4e.png">

**Comment by six7** [comment]
> @six7 to be fair I am not even sure if we should support the older structure because it is too confusing from a file format perspective. It gets too complicated to mix keys like that in my opinion

We'll need to support it somehow. I can imagine an option in the url storage modal asking what type of file this is (jsonbin format or regular)
